/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem.view;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import librarymanagementsystem.model.Borrower;

/**
 *
 * @author lieli
 */
public class Borrowers extends javax.swing.JFrame {
    
    Borrower borrower = new Borrower();

    /**
     * Creates new form Books
     */
    public Borrowers() {
        initComponents();
        borrower.loadBorrowersIntoTable(borrowerData);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDeleteBorrower1 = new javax.swing.JButton();
        txtBorrowerID = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDeleteBorrower = new javax.swing.JButton();
        txtPhoneOrEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        borrowerData = new javax.swing.JTable();
        btnUpdateBorrower = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addBorrower = new javax.swing.JButton();
        checkBoxBorrowers = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 241, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel2.setText("Borrower ID: ");
        jLabel2.setName("lblBorrowerID"); // NOI18N

        btnDeleteBorrower1.setBackground(new java.awt.Color(51, 204, 255));
        btnDeleteBorrower1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnDeleteBorrower1.setText("Back to Dashboard");
        btnDeleteBorrower1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteBorrower1.setBorderPainted(false);
        btnDeleteBorrower1.setName("btnBack"); // NOI18N
        btnDeleteBorrower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBorrower1ActionPerformed(evt);
            }
        });

        txtBorrowerID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtBorrowerID.setName("txtBorrowerD"); // NOI18N

        txtUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUsername.setName("txtUsername"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setText("Username: ");
        jLabel3.setName("lblUsername"); // NOI18N

        txtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtName.setName("txtName"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel4.setText("Name:");
        jLabel4.setName("lblName"); // NOI18N

        btnDeleteBorrower.setBackground(new java.awt.Color(102, 204, 255));
        btnDeleteBorrower.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnDeleteBorrower.setText("Delete Borrower");
        btnDeleteBorrower.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteBorrower.setBorderPainted(false);
        btnDeleteBorrower.setName("btnDelete"); // NOI18N
        btnDeleteBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBorrowerActionPerformed(evt);
            }
        });

        txtPhoneOrEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPhoneOrEmail.setName("txtPhoneEmail"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Borrowers");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setName("lblLibrarySystem"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel5.setText("Phone / Email:");
        jLabel5.setName("lblPhoneEmail"); // NOI18N

        borrowerData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower ID", "Username", "Name", "Phone/Email", "Has Library Card"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        borrowerData.setName("tblBorrowers"); // NOI18N
        borrowerData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowerDataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(borrowerData);

        btnUpdateBorrower.setBackground(new java.awt.Color(102, 204, 255));
        btnUpdateBorrower.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnUpdateBorrower.setText("Update Borrower");
        btnUpdateBorrower.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateBorrower.setBorderPainted(false);
        btnUpdateBorrower.setName("btnUpdate"); // NOI18N
        btnUpdateBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBorrowerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel6.setText("Has Library Card:");
        jLabel6.setName("lblLibraryCard"); // NOI18N

        addBorrower.setBackground(new java.awt.Color(102, 204, 255));
        addBorrower.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        addBorrower.setText("Add New Borrower");
        addBorrower.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBorrower.setBorderPainted(false);
        addBorrower.setName("btnAdd"); // NOI18N
        addBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBorrowerActionPerformed(evt);
            }
        });

        checkBoxBorrowers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        checkBoxBorrowers.setName("cbLibraryCard"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteBorrower1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxBorrowers)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBorrowerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhoneOrEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnDeleteBorrower, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBorrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneOrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxBorrowers, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBorrower)
                    .addComponent(btnUpdateBorrower)
                    .addComponent(btnDeleteBorrower))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteBorrower1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBorrowerID, txtName, txtPhoneOrEmail, txtUsername});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnDeleteBorrower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBorrower1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);

        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_btnDeleteBorrower1ActionPerformed

    private void btnDeleteBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBorrowerActionPerformed
        // TODO add your handling code here:
        int borrowerid = Integer.parseInt(txtBorrowerID.getText());
        borrower.deleteBorrower(borrowerid);
        borrower.loadBorrowersIntoTable(borrowerData);
    }//GEN-LAST:event_btnDeleteBorrowerActionPerformed
    
    private static final String PHONE_REGEX = "^\\d{10}$";
    private static final String GMAIL_REGEX = "^[a-zA-Z0-9._%+-]+@gmail\\.com$";
    
    public boolean isPhoneNumber(String input) {
        return validateWithRegex(input, PHONE_REGEX);
    }

    public boolean isGmailAddress(String input) {
        return validateWithRegex(input, GMAIL_REGEX);
    }

    private boolean validateWithRegex(String input, String regex) {
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(input);
        return matcher.matches();
    }
    
    private void btnUpdateBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBorrowerActionPerformed

         int borrowerId;
         String username = txtUsername.getText().trim();
         String name = txtName.getText().trim();
         String phoneOrEmail = txtPhoneOrEmail.getText().trim();
         Boolean hasLibraryCard = checkBoxBorrowers.isSelected();

         try {
             borrowerId = Integer.parseInt(txtBorrowerID.getText().trim());
         } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, "Borrower ID must be a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
             return;
         }

         if (username.isEmpty() || name.isEmpty()) {
             JOptionPane.showMessageDialog(null, "Username and Name cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
             return; 
         }

         if (!isPhoneNumber(phoneOrEmail) && !isGmailAddress(phoneOrEmail)) {
             JOptionPane.showMessageDialog(null, "Phone or Email must be a valid phone number (10 digits) or a Gmail address.", "Input Error", JOptionPane.ERROR_MESSAGE);
             return; 
         }

         borrower.updateBorrower(borrowerId, username, name, phoneOrEmail, hasLibraryCard);
         borrower.loadBorrowersIntoTable(borrowerData);
    }//GEN-LAST:event_btnUpdateBorrowerActionPerformed

    private void addBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBorrowerActionPerformed
        String username = txtUsername.getText().trim();
        String name = txtName.getText().trim();
        String phoneoremail = txtPhoneOrEmail.getText().trim();
        Boolean hasLibraryCard = checkBoxBorrowers.isSelected();

        if (username.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username and Name cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (!isPhoneNumber(phoneoremail) && !isGmailAddress(phoneoremail)) {
            JOptionPane.showMessageDialog(null, "Phone or Email must be a valid phone number or a Gmail address.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        borrower.addBorrower(username, name, phoneoremail, hasLibraryCard);
        borrower.loadBorrowersIntoTable(borrowerData);
    }//GEN-LAST:event_addBorrowerActionPerformed

    private void borrowerDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerDataMouseClicked
        // TODO add your handling code here:
         // Get the selected row index
    int selectedRow = borrowerData.getSelectedRow();
    
    // Check if a row is actually selected
    if (selectedRow != -1) {
        // Retrieve data from the selected row
        String borrowerID = borrowerData.getValueAt(selectedRow, 0).toString();
        String username = borrowerData.getValueAt(selectedRow, 1).toString();
        String name = borrowerData.getValueAt(selectedRow, 2).toString();
        String phoneOrEmail = borrowerData.getValueAt(selectedRow, 3).toString();
        boolean hasLibraryCard = (Boolean) borrowerData.getValueAt(selectedRow, 4);
        
        // Populate the form fields with the selected row data
        txtBorrowerID.setText(borrowerID);
        txtUsername.setText(username);
        txtName.setText(name);
        txtPhoneOrEmail.setText(phoneOrEmail);
        checkBoxBorrowers.setSelected(hasLibraryCard);
    }
    }//GEN-LAST:event_borrowerDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrowers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBorrower;
    private javax.swing.JTable borrowerData;
    private javax.swing.JButton btnDeleteBorrower;
    private javax.swing.JButton btnDeleteBorrower1;
    private javax.swing.JButton btnUpdateBorrower;
    private javax.swing.JCheckBox checkBoxBorrowers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtBorrowerID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneOrEmail;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
